const cfg=window.TRAVEL_CONFIG||{},sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(s="")=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let trips=[],events=[],budgets=[],world=[];
async function check(){const {data}=await sb.auth.getSession();data.session?showApp():showLogin()}function showLogin(){loginView.hidden=false;adminApp.hidden=true}async function showApp(){loginView.hidden=true;adminApp.hidden=false;await loadAll()}async function login(){loginMsg.textContent="";const {error}=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)return loginMsg.textContent="로그인에 실패했습니다.";showApp()}async function logout(){await sb.auth.signOut();showLogin()}
async function loadAll(){const [t,e,b,w]=await Promise.all([sb.from("travel_trips").select("*").order("start_date"),sb.from("travel_events").select("*").order("event_date"),sb.from("travel_budgets").select("*").order("sort_order"),sb.from("travel_world_places").select("*").order("country")]);trips=t.data||[];events=e.data||[];budgets=b.data||[];world=w.data||[];renderAll()}
function renderAll(){summaryGrid.innerHTML=[["여행",trips.length],["일정",events.length],["예산 항목",budgets.length],["세계 국가",world.length]].map(x=>`<div><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join("");renderTripList();renderEventList();renderBudgetList();renderWorldList();fillTripSelects()}
function acts(type,id){return `<div class="item-actions"><button onclick="edit${type}(${id})">수정</button><button class="delete" onclick="del${type}(${id})">삭제</button></div>`}
function renderTripList(){const q=tripSearch.value.toLowerCase();tripList.innerHTML=trips.filter(x=>!q||(`${x.title} ${x.city||""} ${x.country||""}`).toLowerCase().includes(q)).map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${x.trip_type} · ${x.status} · ${x.start_date||""}</small></div>${acts("Trip",x.id)}</div>`).join("")}
window.editTrip=id=>{const x=trips.find(v=>v.id===id);tripId.value=x.id;tripType.value=x.trip_type;tripStatus.value=x.status;tripTitle.value=x.title;tripStart.value=x.start_date||"";tripEnd.value=x.end_date||"";tripRegion.value=x.region||"";tripCity.value=x.city||"";tripCountry.value=x.country||"";tripMemo.value=x.memo||"";tripVisible.checked=x.is_visible!==false};window.delTrip=async id=>{if(!confirm("삭제하시겠습니까?"))return;await sb.from("travel_trips").delete().eq("id",id);loadAll()}
async function saveTrip(e){e.preventDefault();const id=tripId.value,p={trip_type:tripType.value,status:tripStatus.value,title:tripTitle.value.trim(),start_date:tripStart.value||null,end_date:tripEnd.value||null,region:tripRegion.value.trim(),city:tripCity.value.trim(),country:tripCountry.value.trim(),memo:tripMemo.value.trim(),is_visible:tripVisible.checked,updated_at:new Date().toISOString()},r=id?await sb.from("travel_trips").update(p).eq("id",id):await sb.from("travel_trips").insert(p);if(r.error)alert(r.error.message);else{resetTrip();loadAll()}}
function resetTrip(){tripForm.reset();tripId.value="";tripVisible.checked=true}
function fillTripSelects(){const o='<option value="">미지정</option>'+trips.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join("");eventTrip.innerHTML=o;budgetTrip.innerHTML=o}
function renderEventList(){eventList.innerHTML=events.map(x=>`<div class="item"><div><b>${x.event_date} · ${esc(x.title)}</b><small>${esc(x.category||"")}</small></div>${acts("Event",x.id)}</div>`).join("")}
window.editEvent=id=>{const x=events.find(v=>v.id===id);eventId.value=x.id;eventTrip.value=x.trip_id||"";eventDate.value=x.event_date;eventCategory.value=x.category||"일정";eventTitle.value=x.title;eventDesc.value=x.description||"";eventVisible.checked=x.is_visible!==false};window.delEvent=async id=>{if(!confirm("삭제하시겠습니까?"))return;await sb.from("travel_events").delete().eq("id",id);loadAll()}
async function saveEvent(e){e.preventDefault();const id=eventId.value,p={trip_id:eventTrip.value||null,event_date:eventDate.value,category:eventCategory.value,title:eventTitle.value.trim(),description:eventDesc.value.trim(),is_visible:eventVisible.checked,updated_at:new Date().toISOString()},r=id?await sb.from("travel_events").update(p).eq("id",id):await sb.from("travel_events").insert(p);if(r.error)alert(r.error.message);else{resetEvent();loadAll()}}
function resetEvent(){eventForm.reset();eventId.value="";eventVisible.checked=true;eventCategory.value="일정"}
function renderBudgetList(){budgetListAdmin.innerHTML=budgets.map(x=>`<div class="item"><div><b>${esc(x.category)} · ${Number(x.budget_amount||0).toLocaleString()}원</b><small>지출 ${Number(x.spent_amount||0).toLocaleString()}원</small></div>${acts("Budget",x.id)}</div>`).join("")}
window.editBudget=id=>{const x=budgets.find(v=>v.id===id);budgetId.value=x.id;budgetTrip.value=x.trip_id||"";budgetCategory.value=x.category;budgetAmount.value=x.budget_amount||0;spentAmount.value=x.spent_amount||0;budgetSort.value=x.sort_order||100};window.delBudget=async id=>{if(!confirm("삭제하시겠습니까?"))return;await sb.from("travel_budgets").delete().eq("id",id);loadAll()}
async function saveBudget(e){e.preventDefault();const id=budgetId.value,p={trip_id:budgetTrip.value||null,category:budgetCategory.value,budget_amount:Number(budgetAmount.value)||0,spent_amount:Number(spentAmount.value)||0,sort_order:Number(budgetSort.value)||100,updated_at:new Date().toISOString()},r=id?await sb.from("travel_budgets").update(p).eq("id",id):await sb.from("travel_budgets").insert(p);if(r.error)alert(r.error.message);else{resetBudget();loadAll()}}
function resetBudget(){budgetForm.reset();budgetId.value="";budgetSort.value=100}
function renderWorldList(){worldListAdmin.innerHTML=world.map(x=>`<div class="item"><div><b>${esc(x.country)}</b><small>${x.status} · X ${x.x_percent}% / Y ${x.y_percent}%</small></div>${acts("World",x.id)}</div>`).join("")}
window.editWorld=id=>{const x=world.find(v=>v.id===id);worldId.value=x.id;worldCountryAdmin.value=x.country;worldX.value=x.x_percent;worldY.value=x.y_percent;worldStatus.value=x.status;worldVisible.checked=x.is_visible!==false};window.delWorld=async id=>{if(!confirm("삭제하시겠습니까?"))return;await sb.from("travel_world_places").delete().eq("id",id);loadAll()}
async function saveWorld(e){e.preventDefault();const id=worldId.value,p={country:worldCountryAdmin.value.trim(),x_percent:Number(worldX.value)||50,y_percent:Number(worldY.value)||50,status:worldStatus.value,is_visible:worldVisible.checked,updated_at:new Date().toISOString()},r=id?await sb.from("travel_world_places").update(p).eq("id",id):await sb.from("travel_world_places").insert(p);if(r.error)alert(r.error.message);else{resetWorld();loadAll()}}
function resetWorld(){worldForm.reset();worldId.value="";worldVisible.checked=true}
$$(".admin-side nav button").forEach(b=>b.onclick=()=>{$$(".admin-side nav button").forEach(x=>x.classList.remove("active"));$$(".admin-section").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.target).classList.add("active")});loginBtn.onclick=login;logoutBtn.onclick=logout;tripForm.onsubmit=saveTrip;tripReset.onclick=resetTrip;tripSearch.oninput=renderTripList;eventForm.onsubmit=saveEvent;eventReset.onclick=resetEvent;budgetForm.onsubmit=saveBudget;budgetReset.onclick=resetBudget;worldForm.onsubmit=saveWorld;worldReset.onclick=resetWorld;check();