-- MY TRAVEL PLANNER v2 REAL
create table if not exists public.travel_trips(
 id bigint generated by default as identity primary key,
 trip_type text not null default '국내',
 status text not null default '예정',
 title text not null,
 start_date date,
 end_date date,
 region text default '',
 city text default '',
 country text default '',
 memo text default '',
 is_visible boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.travel_events(
 id bigint generated by default as identity primary key,
 trip_id bigint references public.travel_trips(id) on delete cascade,
 event_date date not null,
 category text not null default '일정',
 title text not null,
 description text default '',
 is_visible boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.travel_budgets(
 id bigint generated by default as identity primary key,
 trip_id bigint references public.travel_trips(id) on delete cascade,
 category text not null,
 budget_amount numeric not null default 0,
 spent_amount numeric not null default 0,
 sort_order integer not null default 100,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists public.travel_regions(
 id bigint generated by default as identity primary key,
 region text not null unique,
 note text default '',
 is_visible boolean not null default true
);

create table if not exists public.travel_world_places(
 id bigint generated by default as identity primary key,
 country text not null unique,
 x_percent numeric not null default 50,
 y_percent numeric not null default 50,
 status text not null default '버킷리스트',
 is_visible boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

alter table public.travel_trips enable row level security;
alter table public.travel_events enable row level security;
alter table public.travel_budgets enable row level security;
alter table public.travel_regions enable row level security;
alter table public.travel_world_places enable row level security;

drop policy if exists "travel_trips_public_read" on public.travel_trips;
create policy "travel_trips_public_read" on public.travel_trips for select using(is_visible=true);
drop policy if exists "travel_events_public_read" on public.travel_events;
create policy "travel_events_public_read" on public.travel_events for select using(is_visible=true);
drop policy if exists "travel_budget_public_read" on public.travel_budgets;
create policy "travel_budget_public_read" on public.travel_budgets for select using(true);
drop policy if exists "travel_regions_public_read" on public.travel_regions;
create policy "travel_regions_public_read" on public.travel_regions for select using(is_visible=true);
drop policy if exists "travel_world_public_read" on public.travel_world_places;
create policy "travel_world_public_read" on public.travel_world_places for select using(is_visible=true);

drop policy if exists "travel_trips_auth_all" on public.travel_trips;
create policy "travel_trips_auth_all" on public.travel_trips for all to authenticated using(true) with check(true);
drop policy if exists "travel_events_auth_all" on public.travel_events;
create policy "travel_events_auth_all" on public.travel_events for all to authenticated using(true) with check(true);
drop policy if exists "travel_budgets_auth_all" on public.travel_budgets;
create policy "travel_budgets_auth_all" on public.travel_budgets for all to authenticated using(true) with check(true);
drop policy if exists "travel_regions_auth_all" on public.travel_regions;
create policy "travel_regions_auth_all" on public.travel_regions for all to authenticated using(true) with check(true);
drop policy if exists "travel_world_auth_all" on public.travel_world_places;
create policy "travel_world_auth_all" on public.travel_world_places for all to authenticated using(true) with check(true);

insert into public.travel_regions(region) values
('서울'),('경기'),('강원'),('충청'),('전라'),('경상'),('제주')
on conflict(region) do nothing;

insert into public.travel_world_places(country,x_percent,y_percent,status)
values
('대한민국',74,35,'방문'),
('일본',82,35,'방문'),
('베트남',76,53,'방문'),
('프랑스',47,31,'버킷리스트'),
('미국',18,32,'버킷리스트'),
('호주',81,78,'버킷리스트')
on conflict(country) do nothing;
